// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "Pattern TryResolve standard .NET (TryParse, TryGetValue). Le paramètre out est idiomatique pour les méthodes Try* retournant un booléen.", Scope = "member", Target = "~M:RAMQ.COM.EnterpriseMessageTransit.Configuration.EndpointResolver.TryResolve(System.String,System.String,System.String,RAMQ.COM.EnterpriseMessageTransit.Configuration.EndpointSettings@)~System.Boolean")]
[assembly: SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "Pattern TryDeserialize standard .NET. Le paramètre out permet au consumer de tester la désérialisation sans exception.", Scope = "member", Target = "~M:RAMQ.COM.EnterpriseMessageTransit.Messaging.Consumer.BaseConsumer`1.TryDeserializeMessage``1(RAMQ.COM.EnterpriseMessageTransit.Messaging.MessageTransitContext{``0}@)~System.Boolean")]
[assembly: SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "Pattern TryDeserialize standard .NET — contrat d'interface pour le consumer.", Scope = "member", Target = "~M:RAMQ.COM.EnterpriseMessageTransit.Messaging.Consumer.IMessageConsumer`1.TryDeserializeMessage``1(RAMQ.COM.EnterpriseMessageTransit.Messaging.MessageTransitContext{``0}@)~System.Boolean")]

[assembly: SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "Pattern TryDeserialize standard .NET — contrat d'interface provider.", Scope = "member", Target = "~M:RAMQ.COM.EnterpriseMessageTransit.Messaging.Providers.IMessagingProvider.TryDeserialize``1(RAMQ.COM.EnterpriseMessageTransit.Messaging.MessageTransitContext{``0}@)~System.Boolean")]
[assembly: SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "Pattern TryDeserialize standard .NET — contrat d'interface provider.", Scope = "member", Target = "~M:RAMQ.COM.EnterpriseMessageTransit.Messaging.Providers.IMessagingProvider.TryDeserialize``1(RAMQ.COM.EnterpriseMessageTransit.Messaging.MessageTransitContext{``0}@)~System.Boolean")]
[assembly: SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "Pattern TryDeserialize standard .NET — contrat d'interface provider générique.", Scope = "member", Target = "~M:RAMQ.COM.EnterpriseMessageTransit.Messaging.Providers.IMessagingProvider`1.TryDeserialize(RAMQ.COM.EnterpriseMessageTransit.Messaging.MessageTransitContext{`0}@)~System.Boolean")]
[assembly: SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "Pattern TryDeserialize standard .NET — contrat consumer non-générique.", Scope = "member", Target = "~M:RAMQ.COM.EnterpriseMessageTransit.Messaging.Consumer.BaseConsumer`1.TryDeserializeMessage(RAMQ.COM.EnterpriseMessageTransit.Messaging.MessageTransitContext{`0}@)~System.Boolean")]
[assembly: SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "Pattern TryDeserialize standard .NET — contrat d'interface consumer non-générique.", Scope = "member", Target = "~M:RAMQ.COM.EnterpriseMessageTransit.Messaging.Consumer.IMessageConsumer`1.TryDeserializeMessage(RAMQ.COM.EnterpriseMessageTransit.Messaging.MessageTransitContext{`0}@)~System.Boolean")]
[assembly: SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "Pattern TryDeserialize standard .NET — contrat d'interface provider générique avec type imbriqué.", Scope = "member", Target = "~M:RAMQ.COM.EnterpriseMessageTransit.Messaging.Providers.IMessagingProvider`1.TryDeserialize``1(RAMQ.COM.EnterpriseMessageTransit.Messaging.MessageTransitContext{``0}@)~System.Boolean")]
[assembly: SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "Pattern TryDeserialize standard .NET — implémentation provider Azure.", Scope = "member", Target = "~M:RAMQ.COM.EnterpriseMessageTransit.Messaging.Providers.Extensions.AzureMessagingProvider.TryDeserialize``1(RAMQ.COM.EnterpriseMessageTransit.Messaging.MessageTransitContext{``0}@)~System.Boolean")]

